### ISSUE TITLE
add shipping contacts

### ISSUE THREAD

**Issue by anshabat** [anshabat/rewooc#39]
## TODO
- [x] separate delivery & payment fieldsets
- [x] add radio - "I am the recipient of the order"
- [x] pass id attribute from FormElement to FormField component's label
- [x] create separate From component and move styles from assets - https://monosnap.com/file/zMpjDMQwH6mNsXcaAye2qk03OO19SR
- [x] create Form.Fieldset separate compontnt
- [x] add shipping fields: first name, last name, phone, email
- [x] add required validation
- [x] add notice textarea field (add field into createOrderAPI, change field to Textarea)
- [x] add email validation
- [x] add phone only number validation
- [x] if shipping to another person - billing the last name is not required

## Materials

- [x] - https://www.freecodecamp.org/news/how-to-work-with-multiple-checkboxes-in-react/
- [x] - https://reactjs.org/docs/forms.html
